# Generated by Django 3.1.4 on 2020-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='ИД сообщения')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер')),
                ('state', models.IntegerField(verbose_name='Статус')),
                ('state_desc', models.CharField(max_length=50, verbose_name='Описание статуса')),
                ('submit_dt', models.DateTimeField(verbose_name='Дата отправки')),
                ('report_dt', models.DateTimeField(verbose_name='Дата доставки')),
            ],
        ),
    ]
