# Generated by Django 3.1.4 on 2020-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_message', '0002_auto_20201216_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessages',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер'),
        ),
    ]
