# Generated by Django 3.1.4 on 2020-12-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_message', '0005_auto_20201222_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
